### PR TITLE
Propose MIT Licence

### PR DESCRIPTION
**Pull request by Pandapip1**
Currently there isn't actually a licence.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I would *personally* prefer CC0 or Unlicensed or WTFPL because they don't require attribution on reuse.  However, I'm also fine with MIT or Apache 2 if that is what others want, since 99% of the time people ignore the attribution requirement anyway.

**Comment by Pandapip1** [comment]
> I would personally prefer CC0 or Unlicense or WTFPL because they don't require attribution on reuse.

MIT does not require attribution, it only requires that the licence be referenced.

**Comment by MicahZoltu** [comment]
Sorry, you are right.  However, that is a requirement that most people don't do so my general argument still stands.  :)

**Comment by Pandapip1** [comment]
Superseded by #54

**Pull request closed without merging**
