### PR TITLE
Run workflow on @eth-bot ping (Fixes #49)

### LINKED ISSUE #49: Manually re-run bot via @eth-bot

### PR DESCRIPTION
**Pull request by Pandapip1**
Completely untested

### CODE REVIEW

**Review by alita-moore — CHANGES_REQUESTED** [review]
This looks good but it won't work because GitHub creates a new workflow for each different event type. So it would result in one passing (or whatever) for a required workflow and then also the old trigger as well. This looks bad and also still prevents auto merging.

The workaround I found previously was to run a separate workflow that would then re-run the thing. Take a look at the workflows for rerunning the bot on review.

**Comment by Pandapip1** [comment]
As a stop-gap, how about I open a pull that puts information on how to re-trigger the bot (e.g. closing and reopening the pull) in EIP-1?

**Comment by MicahZoltu** [comment]
I'm a bit hesitant because I suspect that no one reads the Readme (or EIP-1) and the few people who do probably are experienced EIP editors who already know they can close/reopen to kick things.  Adding more content to the readme/EIP-1 is likely to further reduce the number of people who actually read it.

Do we have reason to believe that this will be a net positive, even after the side effects?

**Comment by Pandapip1** [comment]
> Do we have reason to believe that this will be a net positive

You're probably right. Even if people read the readme and EIP-1 (I certainly did), it's long enough that such a detail will probably be forgotten. I'll close this for now.

**Pull request closed without merging**
