### PR TITLE
Require multiple editor approvals to merge unknown files

### PR DESCRIPTION
**Pull request by Pandapip1**
Fixes https://github.com/ethereum/EIP-Bot/issues/46, Fixes https://github.com/ethereum/EIP-Bot/issues/79

### CODE REVIEW

**Comment by Pandapip1** [comment]
CC @MicahZoltu

**Comment by Pandapip1** [comment]
3 test cases had to be deleted due to them being out-of-date.

**Comment by Pandapip1** [comment]
Finally...

**Comment by Pandapip1** [comment]
@MicahZoltu @axic ready for review.

**Comment by MicahZoltu** [comment]
This does not appear to fix #53 so I removed that from the OP (so it doesn't get auto-closed).  Also, I would like to better understand why we are removing some of these tests.  We also should test this on a fork to make sure it behaves as expected, and possibly add one or more new test cases to cover its behavior.

**Comment by Pandapip1** [comment]
> Also, I would like to better understand why we are removing some of these tests.

They all dealt with approving unknown files with one editor's approval (specifically, the Gemfile).

> Possibly add one or more new test cases to cover its behavior

I've already done that :) (https://github.com/ethereum/EIP-Bot/pull/105/files#diff-b6ddeb8623cdd627ccf86b7b69fb769923e00d0a27fb35869b71492a6027815a)

**Comment by Pandapip1** [comment]
I can confirm that it does *not* merge with a single editor approval, as f2e6aa276e1a418ebfd7d15302f594430b1e8204 didn't pass.

**Comment by Pandapip1** [comment]
I've now added test cases describing every possible condition. **If this passes, it is ready to merge.**

**Comment by MicahZoltu** [comment]
Since we don't have any active maintainers working on the bot at the moment (we are all EIP bot newbs), I would like to see this manually E2E tested before we merge, just to make sure we are generally doing things right.

I believe @JEAlfonsoP is working on doing E2E tests on their fork, perhaps they could test this change (probably easier than testing the many-files change)?  @JEAlfonsoP to this this, update your EIP fork's workflow to point at the latest commit of this branch and then create a PR that touches a non-EIP file and the bot should:
A. post a comment saying that it needs 2 editors to approve.
B. after zero editor approves it should have a red X in the checks section of the PR
C. after one editor approves it should have a red X in the checks section of the PR
D. after two editors approve it should have a green check in the checks section of the PR

**Comment by Pandapip1** [comment]
B implies C unless branch protection is set up incorrectly.

**Comment by JEAlfonsoP** [comment]
I can do that.

**Comment by JEAlfonsoP** [comment]
Workflow is setup to run with this commit. 
I ran several tests and bot responded but I think I do not have a proper test case. Do you have a test case ?

**Comment by Pandapip1** [comment]
I have indeed added E2E tests for all cases (1 author approval, 1 editor approval, and 2 editor approvals) and it passes all of them.

**Comment by Pandapip1** [comment]
Didn't mean to close, oops.

**Comment by MicahZoltu** [comment]
I wouldn't consider the automated tests we have to be E2E.  They are either unit tests or functional tests (people disagree on what this class of tests is called).  E2E usually means you are testing the entire system end to end, which includes real versions of every piece of software being interacted with.  I don't think there is a way to automate this with GitHub, which is why I was hoping that @JEAlfonsoP could do the end to end test manually.

**Comment by MicahZoltu** [comment]
> I ran several tests and bot responded but I think I do not have a proper test case. Do you have a test case ?

Do you have a link to where you ran these tests (the GH action runs)?  The test to do is the one I described above, did it pass all of the various lettered items in that list?

**Comment by Pandapip1** [comment]
I will be more than willing to do these tests once #109 is merged since I have a working test environment.

**Comment by Pandapip1** [comment]
This is going to get tested manually anyways. Merging.

**Pull request merged**
