### PR TITLE
Update PR number logic

### PR DESCRIPTION
**Pull request by Pandapip1**
Blocking https://github.com/ethereum/EIPs/pull/5328

### CODE REVIEW

**Comment by Pandapip1** [comment]
@MicahZoltu I require your approval. Please merge this.

**Comment by MicahZoltu** [comment]
Can you help me understand why this is necessary?  How do we end up in a situation where `context.payload?.pull_request?.number` doesn't exist but `PR_NUMBER` environment variable does?

**Comment by Pandapip1** [comment]
> How do we end up in a situation where context.payload?.pull_request?.number doesn't exist but PR_NUMBER environment variable does?

When the workflow is ran manually.

**Comment by MicahZoltu** [comment]
Hmm, do we have an example of this failing?  Even for manual re-runs, I would expect the PR number to be available for any `pull_request` targeted workflow.

**Comment by Pandapip1** [comment]
> Hmm, do we have an example of this failing? Even for manual re-runs, I would expect the PR number to be available for any pull_request targeted workflow.

Let me be a bit more specific: this is for when we aren't targeting this with `pull_request`. Currently, this is unnecessary. It is preventing me from making some changes, however.

**Comment by MicahZoltu** [comment]
Ah, I see. The idea is to trigger a workflow run, but in order to do that we need to parameterize the inputs since that workflow won't be run in the context of a PR?

**Review by MicahZoltu — APPROVED** [review]

**Pull request merged**
